export {
  createTablePlugin,
  INSERT_TABLE_COMMAND,
  TableNode,
  TableRowNode,
  TableCellNode,
  $createTableNodeWithDimensions,
  $findCellNode,
  $findTableNode,
  $getTableCellNodeFromLexicalNode,
  $getTableNodeFromLexicalNodeOrThrow,
  $getTableRowIndexFromTableCellNode,
  $getTableColumnIndexFromTableCellNode,
  $insertTableColumnAtSelection,
  $insertTableRowAtSelection,
  $deleteTableColumnAtSelection,
  $deleteTableRowAtSelection,
  $setTableRowIsHeader,
  $setTableColumnIsHeader,
  $mergeCells,
  $unmergeCell,
  $isTableNode,
  insertTableRow,
  insertTableColumn,
  deleteTableRow,
  deleteTableColumn,
  toggleTableHeaderRow,
  toggleTableHeaderColumn,
  deleteTable,
  moveTableRow,
  moveTableColumn,
  mergeTableCells,
  unmergeTableCell,
  isTableHeaderColumnActive,
  getTableSelectionBounds,
  canMergeTableCells,
  canUnmergeTableCell,
  setTableCellBackgroundColor,
  getActiveTableCellBackgroundColor,
  setTableCellVerticalAlign,
  getActiveTableCellVerticalAlign,
  setTableAlignment,
  getActiveTableAlignment,
  toggleTableRowStriping,
  isTableRowStripingActive,
  setTableColumnWidth,
  setTableCellWidth,
  setTableRowHeight,
  setTableBorder,
  getActiveTableBorder,
  getActiveTableKey,
  getActiveTableInfo,
  type TablePluginConfig,
  type TableCellVerticalAlign,
  type TableAlign,
  type TableSelectionBounds,
  type TableBorderStyle,
  type TableBorder,
  type TableBorderMode,
} from "./tablePlugin";
